In [1]:
import os
import pandas as pd
import numpy as np
import alpaca_trade_api as tradeapi
# Load .env enviroment variables
from dotenv import load_dotenv
load_dotenv()
import pathlib as Path
import matplotlib.pyplot as plt

In [2]:
# storing alpaca key and secret key in variables 
alpaca_api_key = os.getenv('ALPACA_API_KEY')
alpaca_secret_key = os.getenv('ALPACA_SECRET_KEY')

api = tradeapi.REST(alpaca_api_key,alpaca_secret_key,api_version='V2')

In [3]:
# set time frame
timeframe = '1D'

# start and 'end' date for covid stock market 
start_date_covid = pd.Timestamp('2020-01-01',tz='America/New_York').isoformat()
end_date_covid = pd.Timestamp('2020-11-20',tz='America/New_York').isoformat()

# start and end date for 2008 recession 
start_date_2008 = pd.Timestamp('2007-07-01',tz='America/New_York').isoformat()
end_date_2008 = pd.Timestamp('2009-07-01',tz='America/New_York').isoformat()

# set tickers (per industry)
fast_food_tickers = ['MCD','WEN','YUM','DPZ','CMG']

# get stock data from covid
fastfood_tickers_covid = api.get_barset(fast_food_tickers,timeframe,start=start_date_covid,end = end_date_covid).df

# get stock data from 2008 recession
fastfood_tickers_2008 = api.get_barset(fast_food_tickers,timeframe,start=start_date_2008,end = end_date_2008).df

In [4]:
fastfood_tickers_covid.head()

                              CMG                                        DPZ  \
                             open      high      low   close  volume    open
2020-01-02 00:00:00-05:00  839.97  859.1900  837.530  857.69  386547  293.79
2020-01-03 00:00:00-05:00  853.24  870.9359  853.240  864.95  364633  291.72
2020-01-06 00:00:00-05:00  862.00  862.8000  854.000  857.72  287459  294.00
2020-01-07 00:00:00-05:00  863.00  863.0000  854.392  859.92  175373  291.70
2020-01-08 00:00:00-05:00  856.15  867.0000  856.150  856.59  211756  291.19

                                                            ...    WEN         \
                             high      low   close  volume  ...   open   high
2020-01-02 00:00:00-05:00  295.10  292.130  293.46  450647  ...  22.21  22.37
2020-01-03 00:00:00-05:00  295.26  290.780  294.79  431947  ...  22.25  22.50
2020-01-06 00:00:00-05:00  294.38  291.780  293.88  425843  ...  22.22  22.26
2020-01-07 00:00:00-05:00  293.25  290.880  291.75  440540  ...  22.09  22.12
2020-01-08 00:00:00-05:00  292.20  288.875  290.56  435408  ...  21.91  22.06

                                                     YUM                  \
                             low  close   volume    open    high     low
2020-01-02 00:00:00-05:00  21.96  22.34  1770198  100.90  102.19  100.81
2020-01-03 00:00:00-05:00  22.22  22.37  1450795  101.42  102.01  100.36
2020-01-06 00:00:00-05:00  21.84  22.13  2202358  101.43  101.80  101.06
2020-01-07 00:00:00-05:00  21.81  21.95  2220382  101.75  102.24  101.54
2020-01-08 00:00:00-05:00  21.72  21.72  1968280  100.47  102.98  100.34


                            close   volume
2020-01-02 00:00:00-05:00  102.18   989457
2020-01-03 00:00:00-05:00  101.84   819628
2020-01-06 00:00:00-05:00  101.79  1062267
2020-01-07 00:00:00-05:00  101.97  1007293
2020-01-08 00:00:00-05:00  102.14  1144917

[5 rows x 25 columns]

In [5]:
# create new covid and 2008 dataframe to store ckosing prices of each stock
covid_closingprices_ff = pd.DataFrame()

# get closing prices for all tickers
for ticker in fast_food_tickers:
    covid_closingprices_ff[ticker]=fastfood_tickers_covid[ticker]['close']
    
# drop time component on index
covid_closingprices_ff.index = covid_closingprices_ff.index.date
    
covid_closingprices_ff.head()

               MCD    WEN     YUM     DPZ     CMG
2020-01-02  200.80  22.34  102.18  293.46  857.69
2020-01-03  200.02  22.37  101.84  294.79  864.95
2020-01-06  202.33  22.13  101.79  293.88  857.72
2020-01-07  202.63  21.95  101.97  291.75  859.92
2020-01-08  205.86  21.72  102.14  290.56  856.59

In [6]:
closingprices2008_ff = pd.DataFrame()

# get closing prices for all tickers
for ticker in fast_food_tickers:
    closingprices2008_ff[ticker]=fastfood_tickers_2008[ticker]['close']
    
# drop time component on index
closingprices2008_ff.index = closingprices2008_ff.index.date
    
closingprices2008_ff.head()

              MCD    WEN    YUM    DPZ     CMG
2008-01-02  58.12  25.47  37.90  12.84  146.68
2008-01-03  57.92  24.86  37.31  12.11  141.46
2008-01-04  57.03  23.27  36.85  11.74  127.12
2008-01-07  58.08  23.06  37.62  12.02  123.61
2008-01-08  57.01  22.97  36.63  11.58  117.77

In [7]:
# COVID Fast Food Industry Tickers
covid_closingprices_ff.head()

               MCD    WEN     YUM     DPZ     CMG
2020-01-02  200.80  22.34  102.18  293.46  857.69
2020-01-03  200.02  22.37  101.84  294.79  864.95
2020-01-06  202.33  22.13  101.79  293.88  857.72
2020-01-07  202.63  21.95  101.97  291.75  859.92
2020-01-08  205.86  21.72  102.14  290.56  856.59

In [8]:
# 2008 Entertainment Industry Tickers
closingprices2008_ff.head()

              MCD    WEN    YUM    DPZ     CMG
2008-01-02  58.12  25.47  37.90  12.84  146.68
2008-01-03  57.92  24.86  37.31  12.11  141.46
2008-01-04  57.03  23.27  36.85  11.74  127.12
2008-01-07  58.08  23.06  37.62  12.02  123.61
2008-01-08  57.01  22.97  36.63  11.58  117.77

In [9]:
# daily returns
ff_covid_dr = covid_closingprices_ff.pct_change().dropna()
ff_returns2008 = closingprices2008_ff.pct_change().dropna()

Index(['MCD', 'WEN', 'YUM', 'DPZ', 'CMG'], dtype='object')
Weights
[0.2 0.2 0.2 0.2 0.2]
Expected returns
0.32991833850341856
Expected volatility
0.43884597375920487
Shape ratio
0.7517861806439747

In [18]:
# running 10k simulations on portfolio- COVID FF
number_ports = 100000
ff_covid_all_weights = np.zeros((number_ports, len(covid_closingprices_ff.columns)))
ff_covid_returns_array = np.zeros(number_ports)
ff_covid_volatility_array = np.zeros(number_ports)
ff_covid_sharpe_array = np.zeros(number_ports)

np.random.seed(4)

for index in range(number_ports):
    #weights
    weights = np.array(np.random.random(5))
    weights = weights/np.sum(weights)

    #save weights
    ff_covid_all_weights[index,:] = weights

    #expected returns
    ff_covid_returns_array[index] = np.sum((ff_covid_dr.mean()*weights)*252)

    #expected volatiltiy
    ff_covid_volatility_array[index] = np.sqrt(np.dot(weights.T, np.dot(ff_covid_dr.cov()*252, weights)))

    #sharpe ratio
    ff_covid_sharpe_array[index] = ff_covid_returns_array[index]/ff_covid_volatility_array[index]

In [19]:
# find shape weights by index - COVID FF
ff_covid_sharpe_array.max()

#look at the weights from the index- COVID FF
ff_covid_index_max_shape = ff_covid_sharpe_array.argmax()
ff_covid_index_max_shape

#look at the weights from the index- COVID FF
ff_covid_weights_array = ff_covid_all_weights[ff_covid_index_max_shape,:]
ff_covid_weights_array

array([0.0081001 , 0.02144947, 0.00317154, 0.44037344, 0.52690545])

In [23]:
#Name of stocks in portfolio
print(closingprices2008_ff.columns)

ff_2008_weights = np.full((1, len(closingprices2008_ff.columns)), 1/len(closingprices2008_ff.columns))[0]
print("Weights")
print(ff_2008_weights)

#expect returns
print('Expected returns')
ff_2008_exp_return = np.sum((ff_returns2008.mean()*ff_2008_weights)*252)
print(ff_2008_exp_return)

#expected STD/volatility
print('Expected volatility')
ff_2008_exp_volat = np.sqrt(np.dot(ff_2008_weights.T, np.dot(ff_returns2008.cov()*252, ff_2008_weights)))
print(ff_2008_exp_volat)

#Shape ratio
print('Shape ratio')
ff_2008_sharpe = ff_2008_exp_return/ff_2008_exp_volat
print(ff_2008_sharpe)

Index(['MCD', 'WEN', 'YUM', 'DPZ', 'CMG'], dtype='object')
Weights
[0.2 0.2 0.2 0.2 0.2]
Expected returns
-0.1425421558148248
Expected volatility
0.45501613578875527
Shape ratio
-0.3132683538084484

In [20]:
# running 10k simulations on portfolio - 2008 FF
number_ports = 100000
ff_2008_all_weights = np.zeros((number_ports, len(closingprices2008_ff.columns)))
ff_2008_returns_array = np.zeros(number_ports)
ff_2008_volatility_array = np.zeros(number_ports)
ff_2008_sharpe_array = np.zeros(number_ports)

np.random.seed(4)

for index in range(number_ports):
    #weights
    weights = np.array(np.random.random(5))
    weights = weights/np.sum(weights)

    #save weights
    ff_2008_all_weights[index,:] = weights

    #expected returns
    ff_2008_returns_array[index] = np.sum((ff_returns2008.mean()*weights)*252)

    #expected volatiltiy
    ff_2008_volatility_array[index] = np.sqrt(np.dot(weights.T, np.dot(ff_returns2008.cov()*252, weights)))

    #sharpe ratio
    ff_2008_sharpe_array[index] = ff_2008_returns_array[index]/ff_2008_volatility_array[index]

In [21]:
# find shape weights by index - COVID FF
ff_2008_sharpe_array.max()

#look at the weights from the index- COVID FF
ff_2008_index_max_shape = ff_2008_sharpe_array.argmax()
ff_2008_index_max_shape

90751

In [24]:
#look at the weights from the index- COVID FF
ff_2008_weights_array = ff_2008_all_weights[ff_2008_index_max_shape,:]
ff_2008_weights_array

array([0.51671353, 0.00217503, 0.42314488, 0.04618614, 0.01178043])

In [25]:
#Name of stocks in portfolio - COVID FAST FOOD
print(covid_closingprices_ff.columns)


#expect returns
print('Expected returns')
ff_covid_exp_return = np.sum((ff_covid_dr.mean()*ff_covid_weights_array)*252)
print(ff_covid_exp_return)

#expected STD/volatility
print('Expected volatility')
ff_covid_exp_volat = np.sqrt(np.dot(ff_covid_weights_array.T, np.dot(ff_covid_dr.cov()*252, ff_covid_weights_array)))
print(ff_covid_exp_volat)

#Shape ratio
print('Shape ratio')
ff_covid_sharpe = ff_covid_exp_return/ff_covid_exp_volat
print(ff_covid_sharpe)

Index(['MCD', 'WEN', 'YUM', 'DPZ', 'CMG'], dtype='object')
Expected returns
0.5068341907164335
Expected volatility
0.41182439343581856
Shape ratio
1.2307046372070283

In [32]:
#Name of stocks in portfolio - 2008 FAST FOOD

print(closingprices2008_ff.columns)


#expect returns
print('Expected returns')
ff_2008_exp_return = np.sum((ff_returns2008.mean()*ff_2008_weights_array)*252)
print(ff_covid_exp_return)

#expected STD/volatility
print('Expected volatility')
ff_2008_exp_volat = np.sqrt(np.dot(ff_2008_weights_array.T, np.dot(ff_returns2008.cov()*252, ff_2008_weights_array)))
print(ff_2008_exp_volat)

#Shape ratio
print('Shape ratio')
ff_2008_sharpe = ff_2008_exp_return/ff_2008_exp_volat
print(ff_2008_sharpe)

Index(['MCD', 'WEN', 'YUM', 'DPZ', 'CMG'], dtype='object')
Expected returns
0.5068341907164335
Expected volatility
0.3517487489307539
Shape ratio
0.11630643956234629

In [31]:
weights_array_covid_ff = np.array([0.0081001 , 0.02144947, 0.00317154, 0.44037344, 0.52690545])
ff_covid_weights_array = np.array([0.51671353, 0.00217503, 0.42314488, 0.04618614, 0.01178043])